### ISSUE TITLE
Plugin changes true to True and false to False

### ISSUE THREAD

**Issue by tgb417** [dataiku/dss-plugin-api-connect#13]
I'm pulling data from a REST API that correctly returns the boolean values in Json as true and false (starting in lower case).  However, when the API Connect plugin finishes with the data and puts them in a DSS Dataset the values have True and False (upper case).  This makes parsing the Raw return more difficult.  One has to pre-process the results before one can unnest the resulting JSON.
--Tom

**Comment by alexbourret** [comment]
@tgb417 the latest v1.0.3 should simplify the import and unnesting of json objects.
