### ISSUE TITLE
Allow Bearer Token to be retrieved from Project Variable

### ISSUE THREAD

**Issue by nickheidke** [dataiku/dss-plugin-api-connect#14]
We've got a requirement to enable an Oauth flow for authentication before data can be retrieved. In order to accomplish this, two API calls needs to be made, first, one using username/password auth to get a Bearer Token, then the second call using the Bearer Token to actually get the data from the API. To accomplish this, we could chain two calls to the plugin, or, make the initial API call to get the Bearer token using a python component. The problem is, there's no way to "pass in" the retrieved Bearer Token into the API Connect plugin at runtime. To enable this, we'd like to be able to set the Bearer Token value in the plugin to ${project_variable_name} and have the Bearer Token be pulled from the project (or global) variables.

**Comment by alexbourret** [comment]
Hi !
If you have the token in a project variable name, you can already use it by selecting **No auth** as in login type, then add a header with `Authorization` as key and `Bearer ${project_variable_name}`as value. 

![project_variable_as_bearer_token](https://user-images.githubusercontent.com/3763569/143412673-88702751-5b2d-4c60-9d01-74a82f6099da.png)

If the token changes too often, another way could be to have a first api-connect dataset retrieving the token, isolate it in a column, then use that dataset to feed a api-connect recipe. In that recipe, add the column containing the token in **Columns to use as variables**, and add a header with `Authorization` as key and `Bearer {{token_column_name}}`as value.

**Comment by nickheidke** [comment]
@alexbourret Thank you, this works! This issue can be resolved.

**Comment by alexbourret** [comment]
👍
