### ISSUE TITLE
Request: Return XML results as string

### ISSUE THREAD

**Issue by apd-mharras** [dataiku/dss-plugin-api-connect#45]
I would like to use the API Connect plugin to return results from more than just JSON. It would be great if, when the API returns a non-JSON, the results could be output in a dataset containing one column and one row, where the value is the API results as a string. I could then use all the great features of the plugin and parse the results downstream.

**Comment by alexbourret** [comment]
Hi @apd-mharras ! Can you confirm that you are using version 1.2.2 of the plugin ? Also, is the API you are trying to access public by any chance, so that we can try it from here ?

**Comment by alexbourret** [comment]
👍 I just sent a PM via linkedin
