### ISSUE TITLE
API-Client calling GET instead of POST or PUT

### ISSUE THREAD

**Issue by simonmd** [dataiku/dss-plugin-api-connect#7]
The client is calling a GET request instead of a POST or PUT request, even when selecting the POST or PUT methods in the GUI.

**Configuration:**
<img width="784" alt="Screen Shot 2021-05-24 at 7 58 34 PM" src="https://user-images.githubusercontent.com/155209/119420620-e9fcb300-bcca-11eb-8fdd-9c951b1fdc7d.png">

**Server response** ("read", should be "create" or "update"):
<img width="341" alt="Screen Shot 2021-05-24 at 7 58 52 PM" src="https://user-images.githubusercontent.com/155209/119420628-eff29400-bcca-11eb-9294-6eb3f4179b03.png">

**Comment by alexbourret** [comment]
Hi @simonmd !
Thank you for bringing this bug to our attention. The v1.0.2 release of the plugin is now on the store and should fix it.
