### ISSUE TITLE
Unable to Access Nested Data via Dot Syntax

### ISSUE THREAD

**Issue by nickheidke** [dataiku/dss-plugin-api-connect#9]
I'm getting a response back from an API that looks like this:

`{
	"Data": {
		"XRefCode": "Data_Warehouse_Integration",
		"Rows": [
			{
				"Employee_XRefCode": "5",
				"Job_ShortName": "Nurse",
				"Employee_FirstName": "Melissa"
			},
			{
				"Employee_XRefCode": "7",
				"Job_ShortName": "Nurse",
				"Employee_FirstName": "Nick"
			}
		]
	},
	"Paging": {
		"Next": "https://url-for-next-page-here"
	}
}`

If I set the "Data extraction key" as "Data" I get just two values back, XRefCode and Rows, which I'd expect. However, when I try to then drill to the next level to get the row data via "Data.Rows" I get an exception that no data is found for the extraction key. Am I using the wrong syntax for getting down to the nested Data in this format or is there a bug?

**Comment by alexbourret** [comment]
@nickheidke this issue should be sorted with the new v1.0.3. It is now possible to give a dot separated path instead of the extraction key.
